.job_pre_req: &job_prereq
  before_script:
    - sh -x scripts/ci_puppet_access.sh
    - source ~/.bash_profile
    - rbenv shell 2.3.1
    - bundle install

stages:
  - test
  - deploy

lint:
  <<: *job_prereq
  stage: test
  script:
    - bundle exec rake lint

syntax:
  <<: *job_prereq
  stage: test
  script:
    - bundle exec rake syntax -v

r10ksyntax:
  <<: *job_prereq
  stage: test
  script:
    - bundle exec rake r10k:syntax

deploy_review:
  stage: deploy
  script:
    - echo "Deploying Feature Branch"
    - /opt/puppetlabs/bin/puppet-code deploy -w $CI_BUILD_REF_NAME
  environment:
    name: feature/$CI_BUILD_REF_NAME
    url: http://git.demo.lan/puppet/control-repo/tree/$CI_BUILD_REF_NAME
  only:
    - branches
  except:
    - production

deploy_production:
  stage: deploy
  script:
    - echo "Deploying Feature Branch"
    - /opt/puppetlabs/bin/puppet-code deploy -w production
  environment:
    name: production
    url: http://git.demo.lan/puppet/control-repo/tree/production
  when: manual
  only:
    - production
