before_script:
  - sh -x scripts/ci_puppet_access.sh
  - source ~/.bash_profile
  - rbenv shell 2.3.1
  - bundle install

lint:
  script:
    - bundle exec rake lint

syntax:
  script:
    - bundle exec rake syntax -v

r10ksyntax:
  script:
    - bundle exec rake r10k:syntax
