.job_pre_req: &job_prereq
  before_script:
    - sh -x scripts/ci_puppet_access.sh
    - source ~/.bash_profile
    - rbenv shell 2.3.1
    - bundle install

.deploy_pre_req: &deploy_pre_req
  before_script:
    - sh -x scripts/ci_puppet_access.sh

stages:
  - test
  - deploy

lint:
  <<: *job_prereq
  stage: test
  script:
    - bundle exec rake lint

syntax:
  <<: *job_prereq
  stage: test
  script:
    - bundle exec rake syntax -v

r10ksyntax:
  <<: *job_prereq
  stage: test
  script:
    - bundle exec rake r10k:syntax

deploy_feature:
  <<: *deploy_pre_req
  stage: deploy
  script:
    - echo "Deploying Feature Branch"
    - /opt/puppetlabs/bin/puppet-code deploy -w $CI_BUILD_REF_NAME
  environment:
    name: testing/$CI_BUILD_REF_NAME
    url: http://git.demo.lan/puppet/control-repo/tree/$CI_BUILD_REF_NAME
  only:
    - branches
  except:
    - production
    - qa
    - dev

deploy_dev:
  <<: *deploy_pre_req
  stage: deploy
  script:
    - echo "Deploying DEV Env"
    - /opt/puppetlabs/bin/puppet-code deploy -w dev
  environment:
    name: dev
    url: http://git.demo.lan/puppet/control-repo/tree/dev
  only:
    - dev

deploy_qa:
  <<: *deploy_pre_req
  stage: deploy
  script:
    - echo "Deploying QA Env"
    - /opt/puppetlabs/bin/puppet-code deploy -w qa
  environment:
    name: qa
    url: http://git.demo.lan/puppet/control-repo/tree/qa
  only:
    - qa

deploy_production:
  <<: *deploy_pre_req
  stage: deploy
  script:
    - echo "Deploying Production Env"
    - /opt/puppetlabs/bin/puppet-code deploy -w production
  environment:
    name: production
    url: http://git.demo.lan/puppet/control-repo/tree/production
  when: manual
  only:
    - production
