---
dev:
  rgbank:
    dev-0:
      components:
        Rgbank::Db:
          - rgbank-dev-db.demo.lan
        Rgbank::Web:
          - rgbank-dev-web.demo.lan
        Rgbank::Load:
          - rgbank-dev.demo.lan

staging:
  rgbank:
    staging-0:
      parameters:
        db_username: 'staginguser'
        db_password: 'myawesomepassword'
      components:
        Rgbank::Web:
          - rgbank-appserver-staging-01.demo.lan
        Rgbank::Db:
          - rg-db-staging.demo.lan
        Rgbank::Load:
          - rgbank-staging.demo.lan

production:
  rgbank:
    production-static:
      components:
        Rgbank::Web:
          - rgbank-appserver-01.demo.lan
          - rgbank-appserver-02.demo.lan
        Rgbank::Db:
          - rg-db.demo.lan
        Rgbank::Load:
          - rgbank.demo.lan
  flask_app:
    prod:
      components:
        Flask_app::Webhead:
          - flask_2.demo.lan
    dev:
      components:
        Flask_app::Webhead:
          - flask_1.demo.lan
